=== AcidSepp/internettechnologien-examples/src/main/resources/public/json/lecture-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "http://lecture-schema.json",
  "description": "",
  "type": "object",
  "properties": {
    "$schema": {
      "type": "string"
    },
    "name": {
      "type": "string"
    },
    "semester": {
      "type": "string"
    },
    "course": {
      "type": "string"
    },
    "lecturer": {
      "type": "object",
      "properties": {
        "first-name": {
          "type": "string"
        },
        "last-name": {
          "type": "string"
        },
        "_id": {
          "type": "string"
        }
      },
      "required": [
        "first-name",
        "last-name",
        "_id"
      ],
      "additionalProperties": false
    },
    "books": {
      "type": "array",
      "items": {
        "required": [
          "title",
          "author",
          "year",
          "isbn"
        ],
        "properties": {
          "title": {
            "type": "string"
          },
          "author": {
            "type": "string"
          },
          "year": {
            "type": "string"
          },
          "isbn": {
            "type": "string"
          }
        },
        "additionalProperties": false
      }
    },
    "classes": {
      "type": "array",
      "items": {
        "required": [
          "date",
          "_id"
        ],
        "properties": {
          "date": {
            "type": "string"
          },
          "_id": {
            "type": "string"
          }
        },
        "additionalProperties": false
      }
    }
  },
  "required": [
    "name",
    "semester",
    "course",
    "lecturer",
    "books",
    "classes"
  ],
  "additionalProperties": false
}

=== AcidSepp/internettechnologien-examples/src/main/resources/public/json/lecture.json
{
  "$schema": "lecture-schema.json",
  "name": "Visual Analytics",
  "semester": "SS2025",
  "course": "IF",
  "lecturer": {
    "first-name": "Yannick",
    "last-name": "Weber",
    "_id": "1234"
  },
  "books": [
    {
      "title": "The Visual Display of Quantitative Information",
      "author": "E. Tufte",
      "year": "2001",
      "isbn": "1930824130"
    }
  ],
  "classes": [
    {
      "date": "2025-01-01",
      "_id": "1"
    },
    {
      "date": "2025-01-08",
      "_id": "2"
    }
  ]
}
